/********************************************
	(C) Copyright 2009, 2010, 2011, 2012, 2013, 2014 Sony Corporation
	All Rights Reserved.
*********************************************/
/* SIE CONFIDENTIAL
 ATRAC9(TM) DLL version 4.0.1.1
 *
 *      Copyright (C) 2018 Sony Interactive Entertainment Inc.
 *                        All Rights Reserved.
 *
 */

#include "at9dec.h"
#include "at9sample.h"
#include "at9wave.h"

#include <libatrac9.h>
#include <stdlib.h>
#include <limits.h>



static void _displayDecodeMode(At9Header *pAt9Header);


static int _atracDecCore(FILE      *infile,
						 FILE      *outfile,
						 At9Header *pAt9Header,
						 int       encdelay,
						 int       totalsample,
						 int       nBytePerSample);


int 
at9Dec(FILE *infile,
		FILE *outfile,
		int bitPerSample)
{
	int status = SCE_SUCCESS;
    long totallen;
	int  format, datastart;
	int  encdelay = -1;
    FmtChunk inWaveHeader;
	int nBytePerSample;

	format = parseWaveHeader(infile, &inWaveHeader, &totallen, 
							 &encdelay);

	if (format < 0) {
		DPRINTF("parseWaveHeader() = 0x%x\n", format);
		status = format;
		goto fail;
	}
	if (format != FORMAT_AT9) {
		status = SCE_ERROR_DECODE_ILLEGAL_INPUT_FORMAT;
		goto fail;
	}
	datastart = ftell(infile);
	if (datastart == -1L){
		status = SCE_ERROR_COMMON_FTELL_ERROR;
		goto fail;
	}


	nBytePerSample = bitPerSample / CHAR_BIT;

	_displayDecodeMode(&inWaveHeader.at9Header);

	status = createPcmHeader(outfile,
							 &inWaveHeader,
							 totallen,
							 nBytePerSample);
	if (status < 0) {
		DPRINTF("createPcmHeader() error = 0x%x\n", status);
		goto fail;
	}

	status = _atracDecCore(infile,
						   outfile,
						   &inWaveHeader.at9Header,
						   encdelay, 
						   totallen, 
						   nBytePerSample);
	if (status < 0) {
		DPRINTF("_atracDecCore = 0x%x\n", status);
		goto fail;
	}
fail:
	return status;
}

static void _displayDecodeMode(At9Header *pAt9Header)
{
	int bitrate;

	bitrate = pAt9Header->nAvgBytesPerSec * CHAR_BIT / 1000;
	DPRINTF("Decoding %d kbps (ATRAC9)\n", bitrate);
	return;
}

static int _atracDecCore(FILE      *infile,
						 FILE      *outfile,
						 At9Header *pAt9Header,
						 int       encdelay,
						 int       totalsample,
						 int       nBytePerSample)
{
	HANDLE_ATRAC9 decHandle;
	int status;
	int readBytes;
    int	isf;
	int nch;
	int frameSample;
	int framesInSuperframe;
	int pcmBuffer[SCE_AT9_MAX_FRAME_SAMPLES * SCE_AT9_MAX_CHANNELS];
	unsigned char streamBuf[SCE_AT9_MAX_SUPER_FRAME_SIZE + SCE_AT9_DECODER_INPUT_PADDING];
	int nSamplesDecoded;
	int startsample;
	SceAt9CodecInfo codecInfo;
	unsigned int *reserved = (unsigned int *)pAt9Header->Reserved;

	decHandle = sceAt9GetHandle();

	if (decHandle == NULL) {
		DPRINTF("sceAt9GetHandle() = NULL");
		status = SCE_ERROR_DECODE_CANNOT_GET_HANDLE;
		goto fail;
	}

	switch (pAt9Header->nChannels) {
	case SCE_AT9_CHANNEL_CH4_0:
	case SCE_AT9_CHANNEL_CH5_1:
	case SCE_AT9_CHANNEL_CH7_1:
		switch (*reserved) {
		case AT9_MULTICHVERSION_PARAM_LF:
			DPRINTF("This input file cannot be decoded\n");
			DPRINTF("Input file is ATRAC9 file which is generated by the alpha version tool\n");
			DPRINTF("This file doesn't have compatibility of current at9tool\n");
			status = SCE_ERROR_DECODE_NOT_SUPPORT_PARAMETER;
			goto fail;
			break;
		case AT9_MULTICHVERSION_PARAM_FF:
			DPRINTF("!Warning! : Input file has a special header (Reserved of fmt chunk) temporarily\n");
			break;
		case AT9_MULTICHVERSION_PARAM_CF:
		default:
			break;
		}
		break;
	}
	status = sceAt9DecInit(decHandle,
							pAt9Header->configData,
							(nBytePerSample * CHAR_BIT));
										
	if (status < 0) {
		DPRINTF("sceAt9DecInit() = 0x%x\n", status);
		if ((unsigned int)status == SCE_AT9_ERROR_INTERNAL_ERROR) {
			SceAt9InternalErrorInfo internalErrorInfo;

			sceAt9GetInternalErrorInfo(decHandle, &internalErrorInfo);
			DPRINTF("internalErrorInfo [%d, %d, %d]", internalErrorInfo.errorCode, internalErrorInfo.detailError, internalErrorInfo.detailError);
		}
		goto fail;
	}

	status = sceAt9GetCodecInfo(decHandle,
								&codecInfo);

	if (status < 0) {
		DPRINTF("sceAt9GetCodecInfo() = 0x%x\n", status);
		goto fail;
	}
	nch               = codecInfo.channels;
	framesInSuperframe = codecInfo.framesInSuperframe;
	frameSample       = codecInfo.frameSamples;
	readBytes         = codecInfo.superframeSize;

	/*J set default encoding delay */
	if (encdelay < 0) {
		encdelay = frameSample;
	}
	startsample = encdelay;

	/* Add decdelay */
	startsample += SCE_AT9_DECODER_DELAY_SAMPLES;

	/* Decoding */
	nSamplesDecoded = 0;
    isf = 0;

#ifdef _WIN32
    while (fread_s(streamBuf, (SCE_AT9_MAX_SUPER_FRAME_SIZE + SCE_AT9_DECODER_INPUT_PADDING), readBytes, 1, infile) == 1) {
#else /* _WIN32 */
    while (fread(streamBuf, readBytes, 1, infile) == 1) {
#endif /* _WIN32 */
		int iframe;
		unsigned char *pStream;
		
		pStream  = streamBuf;

		for (iframe = 0; iframe < framesInSuperframe; iframe++) {
			int skipSample, outSample;
			int nbytes_used;

			if (nSamplesDecoded + frameSample <= startsample) {
				skipSample = 0;
				outSample  = 0;
			} else if ((nSamplesDecoded <= startsample)){
				skipSample = startsample % frameSample;
				outSample = frameSample - skipSample;
				if (outSample > totalsample) {
					outSample = totalsample;
				}
			} else if (totalsample < frameSample) {
				skipSample = 0;
				outSample = totalsample;
			} else {
				skipSample = 0;
				outSample = frameSample;
			}

			/* Sound Unit Decoding */
			status = sceAt9DecDecode(decHandle,
									 pStream,
									 &nbytes_used,
									 pcmBuffer,
									 skipSample,
									 outSample);

			if (status < 0) {
				DPRINTF("sceAt9DecDecode() = 0x%x\n", status);
				if ((unsigned int)status == SCE_AT9_ERROR_INTERNAL_ERROR) {
					SceAt9InternalErrorInfo internalErrorInfo;

					sceAt9GetInternalErrorInfo(decHandle, &internalErrorInfo);
					DPRINTF("internalErrorInfo [%d, %d, %d]", internalErrorInfo.errorCode, internalErrorInfo.detailError, internalErrorInfo.detailError);
				}
				goto fail;
			}
			pStream += nbytes_used;
			nSamplesDecoded =  (isf+1) * frameSample;
			isf++;

			if (outSample > 0){
				size_t outputBytes;

				outputBytes = fwrite(pcmBuffer, 
									  nch * nBytePerSample, 
									  outSample, 
									  outfile);
				if ((int)outputBytes < outSample) {
					DPRINTF("output error(PCM Data)\n");
					DPRINTF("outputBytes = %d != decoded_bytes = %d(isf = %d)\n",
						   (int)(outputBytes * nch *2),
						   outSample* nch *2, isf);
					goto fail;
				}
			}
			totalsample -= outSample;
		}
    }
/* Check Bitrate */
    DPRINTF("Decoded Bytes    =%8d Bytes@%dframes(ave=%dbytes)\n",
		   (isf)*readBytes, isf, readBytes);
 fail:
	sceAt9ReleaseHandle(decHandle);
    return status;
}
