/********************************************
	(C) Copyright 2009, 2010, 2011, 2012, 2014, 2015 Sony Corporation
	All Rights Reserved.
*********************************************/
/* SIE CONFIDENTIAL
 ATRAC9(TM) DLL version 4.0.1.1
 *
 *      Copyright (C) 2016 Sony Interactive Entertainment Inc.
 *                        All Rights Reserved.
 *
 */

#include "at9enc.h"
#include "at9sample.h"
#include "at9wave.h"

#include <libatrac9.h>
#include <stdlib.h>
#include <limits.h>


typedef struct {
	int bitrate;
	int ch;
	int dualMode;
	int samplingRate;
	int superframeSize;
	int framesInSuperframe;
	int wlength;
} Atrac9CodecParam;

Atrac9CodecParam gAtracCodecParam[] = {
	/* FORMAT_AT9 Parameter */
	/* bitrate, ch,               dualMode,  samplingRate,       superframeSize, framesInSuperframe,         wlength */
	{ 36,   SCE_AT9_CHANNEL_MONO, TRUE,  SCE_AT9_SAMPLING_RATE_48KHZ,  24*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{ 48,   SCE_AT9_CHANNEL_MONO, TRUE,  SCE_AT9_SAMPLING_RATE_48KHZ,  32*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{ 60,   SCE_AT9_CHANNEL_MONO, TRUE,  SCE_AT9_SAMPLING_RATE_48KHZ,  40*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{ 72,   SCE_AT9_CHANNEL_MONO, TRUE,  SCE_AT9_SAMPLING_RATE_48KHZ,  48*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{ 84,   SCE_AT9_CHANNEL_MONO, TRUE,  SCE_AT9_SAMPLING_RATE_48KHZ,  56*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{ 96,   SCE_AT9_CHANNEL_MONO, TRUE,  SCE_AT9_SAMPLING_RATE_48KHZ,  64*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{120,   SCE_AT9_CHANNEL_MONO, TRUE,  SCE_AT9_SAMPLING_RATE_48KHZ,  80*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{144,   SCE_AT9_CHANNEL_MONO, TRUE,  SCE_AT9_SAMPLING_RATE_48KHZ,  96*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{ 72, SCE_AT9_CHANNEL_STEREO, TRUE,  SCE_AT9_SAMPLING_RATE_48KHZ,  48*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{ 72, SCE_AT9_CHANNEL_STEREO, FALSE, SCE_AT9_SAMPLING_RATE_48KHZ,  48*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{ 96, SCE_AT9_CHANNEL_STEREO, TRUE,  SCE_AT9_SAMPLING_RATE_48KHZ,  64*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{ 96, SCE_AT9_CHANNEL_STEREO, FALSE, SCE_AT9_SAMPLING_RATE_48KHZ,  64*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{120, SCE_AT9_CHANNEL_STEREO, TRUE,  SCE_AT9_SAMPLING_RATE_48KHZ,  80*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{120, SCE_AT9_CHANNEL_STEREO, FALSE, SCE_AT9_SAMPLING_RATE_48KHZ,  80*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{144, SCE_AT9_CHANNEL_STEREO, TRUE,  SCE_AT9_SAMPLING_RATE_48KHZ,  96*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{144, SCE_AT9_CHANNEL_STEREO, FALSE, SCE_AT9_SAMPLING_RATE_48KHZ,  96*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{168, SCE_AT9_CHANNEL_STEREO, TRUE,  SCE_AT9_SAMPLING_RATE_48KHZ, 112*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{168, SCE_AT9_CHANNEL_STEREO, FALSE, SCE_AT9_SAMPLING_RATE_48KHZ, 112*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{192, SCE_AT9_CHANNEL_STEREO, TRUE,  SCE_AT9_SAMPLING_RATE_48KHZ, 128*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{192, SCE_AT9_CHANNEL_STEREO, FALSE, SCE_AT9_SAMPLING_RATE_48KHZ, 128*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{240, SCE_AT9_CHANNEL_STEREO, TRUE,  SCE_AT9_SAMPLING_RATE_48KHZ, 160*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{240, SCE_AT9_CHANNEL_STEREO, FALSE, SCE_AT9_SAMPLING_RATE_48KHZ, 160*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{288, SCE_AT9_CHANNEL_STEREO, TRUE,  SCE_AT9_SAMPLING_RATE_48KHZ, 192*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{288, SCE_AT9_CHANNEL_STEREO, FALSE, SCE_AT9_SAMPLING_RATE_48KHZ, 192*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{192,  SCE_AT9_CHANNEL_CH4_0, FALSE, SCE_AT9_SAMPLING_RATE_48KHZ, 128*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{240,  SCE_AT9_CHANNEL_CH4_0, FALSE, SCE_AT9_SAMPLING_RATE_48KHZ, 160*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{288,  SCE_AT9_CHANNEL_CH4_0, FALSE, SCE_AT9_SAMPLING_RATE_48KHZ, 192*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{384,  SCE_AT9_CHANNEL_CH4_0, FALSE, SCE_AT9_SAMPLING_RATE_48KHZ, 256*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{240,  SCE_AT9_CHANNEL_CH5_1, FALSE, SCE_AT9_SAMPLING_RATE_48KHZ, 160*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{300,  SCE_AT9_CHANNEL_CH5_1, FALSE, SCE_AT9_SAMPLING_RATE_48KHZ, 200*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{360,  SCE_AT9_CHANNEL_CH5_1, FALSE, SCE_AT9_SAMPLING_RATE_48KHZ, 240*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{480,  SCE_AT9_CHANNEL_CH5_1, FALSE, SCE_AT9_SAMPLING_RATE_48KHZ, 320*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{336,  SCE_AT9_CHANNEL_CH7_1, FALSE, SCE_AT9_SAMPLING_RATE_48KHZ, 224*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{420,  SCE_AT9_CHANNEL_CH7_1, FALSE, SCE_AT9_SAMPLING_RATE_48KHZ, 280*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{504,  SCE_AT9_CHANNEL_CH7_1, FALSE, SCE_AT9_SAMPLING_RATE_48KHZ, 336*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{672,  SCE_AT9_CHANNEL_CH7_1, FALSE, SCE_AT9_SAMPLING_RATE_48KHZ, 448*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},

	{ 36,   SCE_AT9_CHANNEL_MONO, TRUE,  SCE_AT9_SAMPLING_RATE_48KHZ,    24,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{ 48,   SCE_AT9_CHANNEL_MONO, TRUE,  SCE_AT9_SAMPLING_RATE_48KHZ,    32,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{ 60,   SCE_AT9_CHANNEL_MONO, TRUE,  SCE_AT9_SAMPLING_RATE_48KHZ,    40,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{ 72,   SCE_AT9_CHANNEL_MONO, TRUE,  SCE_AT9_SAMPLING_RATE_48KHZ,    48,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{ 84,   SCE_AT9_CHANNEL_MONO, TRUE,  SCE_AT9_SAMPLING_RATE_48KHZ,    56,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{ 96,   SCE_AT9_CHANNEL_MONO, TRUE,  SCE_AT9_SAMPLING_RATE_48KHZ,    64,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{120,   SCE_AT9_CHANNEL_MONO, TRUE,  SCE_AT9_SAMPLING_RATE_48KHZ,    80,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{144,   SCE_AT9_CHANNEL_MONO, TRUE,  SCE_AT9_SAMPLING_RATE_48KHZ,    96,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{ 72, SCE_AT9_CHANNEL_STEREO, TRUE,  SCE_AT9_SAMPLING_RATE_48KHZ,    48,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{ 72, SCE_AT9_CHANNEL_STEREO, FALSE, SCE_AT9_SAMPLING_RATE_48KHZ,    48,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{ 96, SCE_AT9_CHANNEL_STEREO, TRUE,  SCE_AT9_SAMPLING_RATE_48KHZ,    64,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{ 96, SCE_AT9_CHANNEL_STEREO, FALSE, SCE_AT9_SAMPLING_RATE_48KHZ,    64,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{120, SCE_AT9_CHANNEL_STEREO, TRUE,  SCE_AT9_SAMPLING_RATE_48KHZ,    80,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{120, SCE_AT9_CHANNEL_STEREO, FALSE, SCE_AT9_SAMPLING_RATE_48KHZ,    80,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{144, SCE_AT9_CHANNEL_STEREO, TRUE,  SCE_AT9_SAMPLING_RATE_48KHZ,    96,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{144, SCE_AT9_CHANNEL_STEREO, FALSE, SCE_AT9_SAMPLING_RATE_48KHZ,    96,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{168, SCE_AT9_CHANNEL_STEREO, TRUE,  SCE_AT9_SAMPLING_RATE_48KHZ,   112,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{168, SCE_AT9_CHANNEL_STEREO, FALSE, SCE_AT9_SAMPLING_RATE_48KHZ,   112,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{192, SCE_AT9_CHANNEL_STEREO, TRUE,  SCE_AT9_SAMPLING_RATE_48KHZ,   128,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{192, SCE_AT9_CHANNEL_STEREO, FALSE, SCE_AT9_SAMPLING_RATE_48KHZ,   128,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{240, SCE_AT9_CHANNEL_STEREO, TRUE,  SCE_AT9_SAMPLING_RATE_48KHZ,   160,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{240, SCE_AT9_CHANNEL_STEREO, FALSE, SCE_AT9_SAMPLING_RATE_48KHZ,   160,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{288, SCE_AT9_CHANNEL_STEREO, TRUE,  SCE_AT9_SAMPLING_RATE_48KHZ,   192,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{288, SCE_AT9_CHANNEL_STEREO, FALSE, SCE_AT9_SAMPLING_RATE_48KHZ,   192,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{192,  SCE_AT9_CHANNEL_CH4_0, FALSE, SCE_AT9_SAMPLING_RATE_48KHZ,   128,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{240,  SCE_AT9_CHANNEL_CH4_0, FALSE, SCE_AT9_SAMPLING_RATE_48KHZ,   160,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{288,  SCE_AT9_CHANNEL_CH4_0, FALSE, SCE_AT9_SAMPLING_RATE_48KHZ,   192,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{384,  SCE_AT9_CHANNEL_CH4_0, FALSE, SCE_AT9_SAMPLING_RATE_48KHZ,   256,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{240,  SCE_AT9_CHANNEL_CH5_1, FALSE, SCE_AT9_SAMPLING_RATE_48KHZ,   160,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{300,  SCE_AT9_CHANNEL_CH5_1, FALSE, SCE_AT9_SAMPLING_RATE_48KHZ,   200,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{360,  SCE_AT9_CHANNEL_CH5_1, FALSE, SCE_AT9_SAMPLING_RATE_48KHZ,   240,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{480,  SCE_AT9_CHANNEL_CH5_1, FALSE, SCE_AT9_SAMPLING_RATE_48KHZ,   320,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{336,  SCE_AT9_CHANNEL_CH7_1, FALSE, SCE_AT9_SAMPLING_RATE_48KHZ,   224,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{420,  SCE_AT9_CHANNEL_CH7_1, FALSE, SCE_AT9_SAMPLING_RATE_48KHZ,   280,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{504,  SCE_AT9_CHANNEL_CH7_1, FALSE, SCE_AT9_SAMPLING_RATE_48KHZ,   336,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{672,  SCE_AT9_CHANNEL_CH7_1, FALSE, SCE_AT9_SAMPLING_RATE_48KHZ,   448,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},

	{ 36,   SCE_AT9_CHANNEL_MONO, TRUE,  SCE_AT9_SAMPLING_RATE_24KHZ,  24*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{ 48,   SCE_AT9_CHANNEL_MONO, TRUE,  SCE_AT9_SAMPLING_RATE_24KHZ,  32*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{ 60,   SCE_AT9_CHANNEL_MONO, TRUE,  SCE_AT9_SAMPLING_RATE_24KHZ,  40*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{ 72,   SCE_AT9_CHANNEL_MONO, TRUE,  SCE_AT9_SAMPLING_RATE_24KHZ,  48*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{ 84,   SCE_AT9_CHANNEL_MONO, TRUE,  SCE_AT9_SAMPLING_RATE_24KHZ,  56*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{ 96,   SCE_AT9_CHANNEL_MONO, TRUE,  SCE_AT9_SAMPLING_RATE_24KHZ,  64*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{120,   SCE_AT9_CHANNEL_MONO, TRUE,  SCE_AT9_SAMPLING_RATE_24KHZ,  80*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{144,   SCE_AT9_CHANNEL_MONO, TRUE,  SCE_AT9_SAMPLING_RATE_24KHZ,  96*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{ 72, SCE_AT9_CHANNEL_STEREO, TRUE,  SCE_AT9_SAMPLING_RATE_24KHZ,  48*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{ 72, SCE_AT9_CHANNEL_STEREO, FALSE, SCE_AT9_SAMPLING_RATE_24KHZ,  48*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{ 96, SCE_AT9_CHANNEL_STEREO, TRUE,  SCE_AT9_SAMPLING_RATE_24KHZ,  64*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{ 96, SCE_AT9_CHANNEL_STEREO, FALSE, SCE_AT9_SAMPLING_RATE_24KHZ,  64*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{120, SCE_AT9_CHANNEL_STEREO, TRUE,  SCE_AT9_SAMPLING_RATE_24KHZ,  80*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{120, SCE_AT9_CHANNEL_STEREO, FALSE, SCE_AT9_SAMPLING_RATE_24KHZ,  80*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{144, SCE_AT9_CHANNEL_STEREO, TRUE,  SCE_AT9_SAMPLING_RATE_24KHZ,  96*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{144, SCE_AT9_CHANNEL_STEREO, FALSE, SCE_AT9_SAMPLING_RATE_24KHZ,  96*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{168, SCE_AT9_CHANNEL_STEREO, TRUE,  SCE_AT9_SAMPLING_RATE_24KHZ, 112*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{168, SCE_AT9_CHANNEL_STEREO, FALSE, SCE_AT9_SAMPLING_RATE_24KHZ, 112*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{192, SCE_AT9_CHANNEL_STEREO, TRUE,  SCE_AT9_SAMPLING_RATE_24KHZ, 128*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{192, SCE_AT9_CHANNEL_STEREO, FALSE, SCE_AT9_SAMPLING_RATE_24KHZ, 128*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{240, SCE_AT9_CHANNEL_STEREO, TRUE,  SCE_AT9_SAMPLING_RATE_24KHZ, 160*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{240, SCE_AT9_CHANNEL_STEREO, FALSE, SCE_AT9_SAMPLING_RATE_24KHZ, 160*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{288, SCE_AT9_CHANNEL_STEREO, TRUE,  SCE_AT9_SAMPLING_RATE_24KHZ, 192*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{288, SCE_AT9_CHANNEL_STEREO, FALSE, SCE_AT9_SAMPLING_RATE_24KHZ, 192*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{192,  SCE_AT9_CHANNEL_CH4_0, FALSE, SCE_AT9_SAMPLING_RATE_24KHZ, 128*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{240,  SCE_AT9_CHANNEL_CH4_0, FALSE, SCE_AT9_SAMPLING_RATE_24KHZ, 160*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{288,  SCE_AT9_CHANNEL_CH4_0, FALSE, SCE_AT9_SAMPLING_RATE_24KHZ, 192*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{384,  SCE_AT9_CHANNEL_CH4_0, FALSE, SCE_AT9_SAMPLING_RATE_24KHZ, 256*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{240,  SCE_AT9_CHANNEL_CH5_1, FALSE, SCE_AT9_SAMPLING_RATE_24KHZ, 160*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{300,  SCE_AT9_CHANNEL_CH5_1, FALSE, SCE_AT9_SAMPLING_RATE_24KHZ, 200*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{360,  SCE_AT9_CHANNEL_CH5_1, FALSE, SCE_AT9_SAMPLING_RATE_24KHZ, 240*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{480,  SCE_AT9_CHANNEL_CH5_1, FALSE, SCE_AT9_SAMPLING_RATE_24KHZ, 320*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{336,  SCE_AT9_CHANNEL_CH7_1, FALSE, SCE_AT9_SAMPLING_RATE_24KHZ, 224*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{420,  SCE_AT9_CHANNEL_CH7_1, FALSE, SCE_AT9_SAMPLING_RATE_24KHZ, 280*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{504,  SCE_AT9_CHANNEL_CH7_1, FALSE, SCE_AT9_SAMPLING_RATE_24KHZ, 336*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{672,  SCE_AT9_CHANNEL_CH7_1, FALSE, SCE_AT9_SAMPLING_RATE_24KHZ, 448*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},

	{ 36,   SCE_AT9_CHANNEL_MONO, TRUE,  SCE_AT9_SAMPLING_RATE_24KHZ,    24,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{ 48,   SCE_AT9_CHANNEL_MONO, TRUE,  SCE_AT9_SAMPLING_RATE_24KHZ,    32,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{ 60,   SCE_AT9_CHANNEL_MONO, TRUE,  SCE_AT9_SAMPLING_RATE_24KHZ,    40,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{ 72,   SCE_AT9_CHANNEL_MONO, TRUE,  SCE_AT9_SAMPLING_RATE_24KHZ,    48,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{ 84,   SCE_AT9_CHANNEL_MONO, TRUE,  SCE_AT9_SAMPLING_RATE_24KHZ,    56,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{ 96,   SCE_AT9_CHANNEL_MONO, TRUE,  SCE_AT9_SAMPLING_RATE_24KHZ,    64,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{120,   SCE_AT9_CHANNEL_MONO, TRUE,  SCE_AT9_SAMPLING_RATE_24KHZ,    80,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{144,   SCE_AT9_CHANNEL_MONO, TRUE,  SCE_AT9_SAMPLING_RATE_24KHZ,    96,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{ 72, SCE_AT9_CHANNEL_STEREO, TRUE,  SCE_AT9_SAMPLING_RATE_24KHZ,    48,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{ 72, SCE_AT9_CHANNEL_STEREO, FALSE, SCE_AT9_SAMPLING_RATE_24KHZ,    48,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{ 96, SCE_AT9_CHANNEL_STEREO, TRUE,  SCE_AT9_SAMPLING_RATE_24KHZ,    64,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{ 96, SCE_AT9_CHANNEL_STEREO, FALSE, SCE_AT9_SAMPLING_RATE_24KHZ,    64,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{120, SCE_AT9_CHANNEL_STEREO, TRUE,  SCE_AT9_SAMPLING_RATE_24KHZ,    80,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{120, SCE_AT9_CHANNEL_STEREO, FALSE, SCE_AT9_SAMPLING_RATE_24KHZ,    80,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{144, SCE_AT9_CHANNEL_STEREO, TRUE,  SCE_AT9_SAMPLING_RATE_24KHZ,    96,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{144, SCE_AT9_CHANNEL_STEREO, FALSE, SCE_AT9_SAMPLING_RATE_24KHZ,    96,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{168, SCE_AT9_CHANNEL_STEREO, TRUE,  SCE_AT9_SAMPLING_RATE_24KHZ,   112,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{168, SCE_AT9_CHANNEL_STEREO, FALSE, SCE_AT9_SAMPLING_RATE_24KHZ,   112,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{192, SCE_AT9_CHANNEL_STEREO, TRUE,  SCE_AT9_SAMPLING_RATE_24KHZ,   128,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{192, SCE_AT9_CHANNEL_STEREO, FALSE, SCE_AT9_SAMPLING_RATE_24KHZ,   128,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{240, SCE_AT9_CHANNEL_STEREO, TRUE,  SCE_AT9_SAMPLING_RATE_24KHZ,   160,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{240, SCE_AT9_CHANNEL_STEREO, FALSE, SCE_AT9_SAMPLING_RATE_24KHZ,   160,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{288, SCE_AT9_CHANNEL_STEREO, TRUE,  SCE_AT9_SAMPLING_RATE_24KHZ,   192,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{288, SCE_AT9_CHANNEL_STEREO, FALSE, SCE_AT9_SAMPLING_RATE_24KHZ,   192,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{192,  SCE_AT9_CHANNEL_CH4_0, FALSE, SCE_AT9_SAMPLING_RATE_24KHZ,   128,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{240,  SCE_AT9_CHANNEL_CH4_0, FALSE, SCE_AT9_SAMPLING_RATE_24KHZ,   160,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{288,  SCE_AT9_CHANNEL_CH4_0, FALSE, SCE_AT9_SAMPLING_RATE_24KHZ,   192,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{384,  SCE_AT9_CHANNEL_CH4_0, FALSE, SCE_AT9_SAMPLING_RATE_24KHZ,   256,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{240,  SCE_AT9_CHANNEL_CH5_1, FALSE, SCE_AT9_SAMPLING_RATE_24KHZ,   160,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{300,  SCE_AT9_CHANNEL_CH5_1, FALSE, SCE_AT9_SAMPLING_RATE_24KHZ,   200,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{360,  SCE_AT9_CHANNEL_CH5_1, FALSE, SCE_AT9_SAMPLING_RATE_24KHZ,   240,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{480,  SCE_AT9_CHANNEL_CH5_1, FALSE, SCE_AT9_SAMPLING_RATE_24KHZ,   320,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{336,  SCE_AT9_CHANNEL_CH7_1, FALSE, SCE_AT9_SAMPLING_RATE_24KHZ,   224,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{420,  SCE_AT9_CHANNEL_CH7_1, FALSE, SCE_AT9_SAMPLING_RATE_24KHZ,   280,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{504,  SCE_AT9_CHANNEL_CH7_1, FALSE, SCE_AT9_SAMPLING_RATE_24KHZ,   336,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{672,  SCE_AT9_CHANNEL_CH7_1, FALSE, SCE_AT9_SAMPLING_RATE_24KHZ,   448,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},

	{ 36,   SCE_AT9_CHANNEL_MONO, TRUE,  SCE_AT9_SAMPLING_RATE_12KHZ,  24*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{ 48,   SCE_AT9_CHANNEL_MONO, TRUE,  SCE_AT9_SAMPLING_RATE_12KHZ,  32*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{ 60,   SCE_AT9_CHANNEL_MONO, TRUE,  SCE_AT9_SAMPLING_RATE_12KHZ,  40*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{ 72,   SCE_AT9_CHANNEL_MONO, TRUE,  SCE_AT9_SAMPLING_RATE_12KHZ,  48*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{ 84,   SCE_AT9_CHANNEL_MONO, TRUE,  SCE_AT9_SAMPLING_RATE_12KHZ,  56*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{ 96,   SCE_AT9_CHANNEL_MONO, TRUE,  SCE_AT9_SAMPLING_RATE_12KHZ,  64*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{120,   SCE_AT9_CHANNEL_MONO, TRUE,  SCE_AT9_SAMPLING_RATE_12KHZ,  80*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{144,   SCE_AT9_CHANNEL_MONO, TRUE,  SCE_AT9_SAMPLING_RATE_12KHZ,  96*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{ 72, SCE_AT9_CHANNEL_STEREO, TRUE,  SCE_AT9_SAMPLING_RATE_12KHZ,  48*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{ 72, SCE_AT9_CHANNEL_STEREO, FALSE, SCE_AT9_SAMPLING_RATE_12KHZ,  48*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{ 96, SCE_AT9_CHANNEL_STEREO, TRUE,  SCE_AT9_SAMPLING_RATE_12KHZ,  64*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{ 96, SCE_AT9_CHANNEL_STEREO, FALSE, SCE_AT9_SAMPLING_RATE_12KHZ,  64*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{120, SCE_AT9_CHANNEL_STEREO, TRUE,  SCE_AT9_SAMPLING_RATE_12KHZ,  80*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{120, SCE_AT9_CHANNEL_STEREO, FALSE, SCE_AT9_SAMPLING_RATE_12KHZ,  80*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{144, SCE_AT9_CHANNEL_STEREO, TRUE,  SCE_AT9_SAMPLING_RATE_12KHZ,  96*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{144, SCE_AT9_CHANNEL_STEREO, FALSE, SCE_AT9_SAMPLING_RATE_12KHZ,  96*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{168, SCE_AT9_CHANNEL_STEREO, TRUE,  SCE_AT9_SAMPLING_RATE_12KHZ, 112*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{168, SCE_AT9_CHANNEL_STEREO, FALSE, SCE_AT9_SAMPLING_RATE_12KHZ, 112*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{192, SCE_AT9_CHANNEL_STEREO, TRUE,  SCE_AT9_SAMPLING_RATE_12KHZ, 128*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{192, SCE_AT9_CHANNEL_STEREO, FALSE, SCE_AT9_SAMPLING_RATE_12KHZ, 128*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{240, SCE_AT9_CHANNEL_STEREO, TRUE,  SCE_AT9_SAMPLING_RATE_12KHZ, 160*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{240, SCE_AT9_CHANNEL_STEREO, FALSE, SCE_AT9_SAMPLING_RATE_12KHZ, 160*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{288, SCE_AT9_CHANNEL_STEREO, TRUE,  SCE_AT9_SAMPLING_RATE_12KHZ, 192*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{288, SCE_AT9_CHANNEL_STEREO, FALSE, SCE_AT9_SAMPLING_RATE_12KHZ, 192*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{192,  SCE_AT9_CHANNEL_CH4_0, FALSE, SCE_AT9_SAMPLING_RATE_12KHZ, 128*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{240,  SCE_AT9_CHANNEL_CH4_0, FALSE, SCE_AT9_SAMPLING_RATE_12KHZ, 160*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{288,  SCE_AT9_CHANNEL_CH4_0, FALSE, SCE_AT9_SAMPLING_RATE_12KHZ, 192*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{384,  SCE_AT9_CHANNEL_CH4_0, FALSE, SCE_AT9_SAMPLING_RATE_12KHZ, 256*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{240,  SCE_AT9_CHANNEL_CH5_1, FALSE, SCE_AT9_SAMPLING_RATE_12KHZ, 160*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{300,  SCE_AT9_CHANNEL_CH5_1, FALSE, SCE_AT9_SAMPLING_RATE_12KHZ, 200*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{360,  SCE_AT9_CHANNEL_CH5_1, FALSE, SCE_AT9_SAMPLING_RATE_12KHZ, 240*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{480,  SCE_AT9_CHANNEL_CH5_1, FALSE, SCE_AT9_SAMPLING_RATE_12KHZ, 320*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{336,  SCE_AT9_CHANNEL_CH7_1, FALSE, SCE_AT9_SAMPLING_RATE_12KHZ, 224*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{420,  SCE_AT9_CHANNEL_CH7_1, FALSE, SCE_AT9_SAMPLING_RATE_12KHZ, 280*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{504,  SCE_AT9_CHANNEL_CH7_1, FALSE, SCE_AT9_SAMPLING_RATE_12KHZ, 336*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{672,  SCE_AT9_CHANNEL_CH7_1, FALSE, SCE_AT9_SAMPLING_RATE_12KHZ, 448*4, SCE_AT9_4FRAMES_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},

	{ 36,   SCE_AT9_CHANNEL_MONO, TRUE,  SCE_AT9_SAMPLING_RATE_12KHZ,    24,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{ 48,   SCE_AT9_CHANNEL_MONO, TRUE,  SCE_AT9_SAMPLING_RATE_12KHZ,    32,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{ 60,   SCE_AT9_CHANNEL_MONO, TRUE,  SCE_AT9_SAMPLING_RATE_12KHZ,    40,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{ 72,   SCE_AT9_CHANNEL_MONO, TRUE,  SCE_AT9_SAMPLING_RATE_12KHZ,    48,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{ 84,   SCE_AT9_CHANNEL_MONO, TRUE,  SCE_AT9_SAMPLING_RATE_12KHZ,    56,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{ 96,   SCE_AT9_CHANNEL_MONO, TRUE,  SCE_AT9_SAMPLING_RATE_12KHZ,    64,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{120,   SCE_AT9_CHANNEL_MONO, TRUE,  SCE_AT9_SAMPLING_RATE_12KHZ,    80,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{144,   SCE_AT9_CHANNEL_MONO, TRUE,  SCE_AT9_SAMPLING_RATE_12KHZ,    96,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{ 72, SCE_AT9_CHANNEL_STEREO, TRUE,  SCE_AT9_SAMPLING_RATE_12KHZ,    48,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{ 72, SCE_AT9_CHANNEL_STEREO, FALSE, SCE_AT9_SAMPLING_RATE_12KHZ,    48,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{ 96, SCE_AT9_CHANNEL_STEREO, TRUE,  SCE_AT9_SAMPLING_RATE_12KHZ,    64,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{ 96, SCE_AT9_CHANNEL_STEREO, FALSE, SCE_AT9_SAMPLING_RATE_12KHZ,    64,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{120, SCE_AT9_CHANNEL_STEREO, TRUE,  SCE_AT9_SAMPLING_RATE_12KHZ,    80,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{120, SCE_AT9_CHANNEL_STEREO, FALSE, SCE_AT9_SAMPLING_RATE_12KHZ,    80,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{144, SCE_AT9_CHANNEL_STEREO, TRUE,  SCE_AT9_SAMPLING_RATE_12KHZ,    96,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{144, SCE_AT9_CHANNEL_STEREO, FALSE, SCE_AT9_SAMPLING_RATE_12KHZ,    96,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{168, SCE_AT9_CHANNEL_STEREO, TRUE,  SCE_AT9_SAMPLING_RATE_12KHZ,   112,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{168, SCE_AT9_CHANNEL_STEREO, FALSE, SCE_AT9_SAMPLING_RATE_12KHZ,   112,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{192, SCE_AT9_CHANNEL_STEREO, TRUE,  SCE_AT9_SAMPLING_RATE_12KHZ,   128,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{192, SCE_AT9_CHANNEL_STEREO, FALSE, SCE_AT9_SAMPLING_RATE_12KHZ,   128,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{240, SCE_AT9_CHANNEL_STEREO, TRUE,  SCE_AT9_SAMPLING_RATE_12KHZ,   160,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{240, SCE_AT9_CHANNEL_STEREO, FALSE, SCE_AT9_SAMPLING_RATE_12KHZ,   160,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{288, SCE_AT9_CHANNEL_STEREO, TRUE,  SCE_AT9_SAMPLING_RATE_12KHZ,   192,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{288, SCE_AT9_CHANNEL_STEREO, FALSE, SCE_AT9_SAMPLING_RATE_12KHZ,   192,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{192,  SCE_AT9_CHANNEL_CH4_0, FALSE, SCE_AT9_SAMPLING_RATE_12KHZ,   128,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{240,  SCE_AT9_CHANNEL_CH4_0, FALSE, SCE_AT9_SAMPLING_RATE_12KHZ,   160,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{288,  SCE_AT9_CHANNEL_CH4_0, FALSE, SCE_AT9_SAMPLING_RATE_12KHZ,   192,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{384,  SCE_AT9_CHANNEL_CH4_0, FALSE, SCE_AT9_SAMPLING_RATE_12KHZ,   256,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{240,  SCE_AT9_CHANNEL_CH5_1, FALSE, SCE_AT9_SAMPLING_RATE_12KHZ,   160,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{300,  SCE_AT9_CHANNEL_CH5_1, FALSE, SCE_AT9_SAMPLING_RATE_12KHZ,   200,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{360,  SCE_AT9_CHANNEL_CH5_1, FALSE, SCE_AT9_SAMPLING_RATE_12KHZ,   240,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{480,  SCE_AT9_CHANNEL_CH5_1, FALSE, SCE_AT9_SAMPLING_RATE_12KHZ,   320,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{336,  SCE_AT9_CHANNEL_CH7_1, FALSE, SCE_AT9_SAMPLING_RATE_12KHZ,   224,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{420,  SCE_AT9_CHANNEL_CH7_1, FALSE, SCE_AT9_SAMPLING_RATE_12KHZ,   280,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{504,  SCE_AT9_CHANNEL_CH7_1, FALSE, SCE_AT9_SAMPLING_RATE_12KHZ,   336,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},
	{672,  SCE_AT9_CHANNEL_CH7_1, FALSE, SCE_AT9_SAMPLING_RATE_12KHZ,   448,  SCE_AT9_1FRAME_IN_SUPER_FRAME, SCE_AT9_WORD_LENGTH_16BIT},


};


static int _getAtracEncodeSetting(int bitrate,
							     int supframe,
							     int dualMode,
							     FmtChunk *pInWaveHeader,
							     Atrac9CodecParam **ppAtracCodecParam);

static int _checkEncodeParam(int format, 
						     FmtChunk *pInWaveHeader,
							 int totallen);

static int _checkEncodeExParam(int nbands,
							   int isband,
							   int gradmode);

static void _displaySupportParam(void);

static void _displayEncodeMode(Atrac9CodecParam *pAtracCodecParam);


static int _atracEncCore(FILE *infile,
						 FILE *outfile,
						 Atrac9CodecParam *pAtracCodecParam,
						 int  dualMode,
						 int  nbands,
						 int  isband,
						 int  gradMode,
					     int  inputlength,
						 int  origlength,
						 int  wband,
						 int  bex,
						 int  slc);


int at9Enc(FILE *infile,
		   FILE *outfile,
		   int  bitrate,
		   int  supframe,
		   int  dualMode,
		   int  nbands,
		   int  isband,
		   int  gradMode,
		   int  wband,
		   int  bex,
		   int  slc)
{
	int status = SCE_SUCCESS;

	int format;
	int encdelay = -1;
    long totallen;
    FmtChunk inWaveHeader;
	int origlen;
	Atrac9CodecParam *pAtracCodecParam = NULL;
 
	format = parseWaveHeader(infile, &inWaveHeader, &totallen, &encdelay);

	if (format < 0) {
		DPRINTF("parseWaveHeader() = 0x%x\n", format);
		status = format;
		goto fail;
	}

	status = _getAtracEncodeSetting(bitrate,
							        supframe,
								    dualMode,
					                &inWaveHeader, 
								    (Atrac9CodecParam **)&pAtracCodecParam);
	
	if (status < 0) {
		DPRINTF("_getAtracEncodeSetting() = 0x%x\n", status);
		goto fail;
	}

	origlen = totallen;
	status = _checkEncodeParam(format,
							  &inWaveHeader,
		                      totallen);
	if (status < 0) {
		DPRINTF("_checkEncodeParam() = 0x%x\n", status);
		goto fail;
	}
	status = _checkEncodeExParam(nbands, isband, gradMode);
	if (status < 0) {
		DPRINTF("_checkEncodeExParam() = 0x%x\n", status);
		goto fail;
	}

	_displayEncodeMode(pAtracCodecParam);

	status = _atracEncCore(infile,
						   outfile,
						   pAtracCodecParam,
						   dualMode,
						   nbands,
						   isband,
						   gradMode,
						   totallen,
						   origlen,
						   wband,
						   bex,
						   slc);
	if (status < 0) {
		DPRINTF("_atracEncCore() = 0x%x\n", status);
		goto fail;
	}

fail:
	return status;
}

static int 
_getAtracEncodeSetting(int bitrate,
					   int supframe,
					   int dualMode,
					   FmtChunk *pInWaveHeader,
					   Atrac9CodecParam **ppAtracCodecParam)
{
	int index, nCodecIndex;
	int status = SCE_SUCCESS;
	int framesInSuperframe;
	
	if (supframe) {
		framesInSuperframe = 4;
	} else {
		framesInSuperframe = 1;
	}

	nCodecIndex = sizeof(gAtracCodecParam) / sizeof(Atrac9CodecParam);
	
	switch (pInWaveHeader->pcmextHeader.nChannels) {
	case SCE_AT9_CHANNEL_MONO:
		dualMode = TRUE;
		break;
	case SCE_AT9_CHANNEL_CH4_0:
	case SCE_AT9_CHANNEL_CH5_1:
	case SCE_AT9_CHANNEL_CH7_1:
		dualMode = FALSE;
		break;
	case SCE_AT9_CHANNEL_STEREO:
	default:
		break;
	}
	
	for (index = 0; index < nCodecIndex; index++) {
		if ((gAtracCodecParam[index].bitrate      == bitrate)
			&& (gAtracCodecParam[index].ch        == pInWaveHeader->pcmHeader.nChannels)
			&& (gAtracCodecParam[index].dualMode      == dualMode)
			&& (gAtracCodecParam[index].samplingRate        == (int)pInWaveHeader->pcmHeader.nSamplesPerSec)
			&& (gAtracCodecParam[index].framesInSuperframe == framesInSuperframe)) {

				gAtracCodecParam[index].wlength = pInWaveHeader->pcmHeader.wBitsPerSample;
				*ppAtracCodecParam = &gAtracCodecParam[index];
				break;
		}
	}

	if (index == nCodecIndex) {
		DPRINTF("Not Supported Param\n\n");
		DPRINTF("bitrate = %3d[kbps], Ch = %1d[ch], Sampling Rate = %5d[Hz]\n", 
			   bitrate, 
			   pInWaveHeader->pcmHeader.nChannels, 
			   (int)pInWaveHeader->pcmHeader.nSamplesPerSec);
		_displaySupportParam();
		DPRINTF("\n");
		status = SCE_ERROR_ENCODE_NOT_SUPPORT_PARAMETER;
	}
	return status;
}

static int _checkEncodeParam(int format, 
						     FmtChunk *pInWaveHeader,
							 int totallen)
{
	int status = SCE_SUCCESS;

	switch (format) {
	case FORMAT_PCM:
		if ((pInWaveHeader->pcmHeader.wBitsPerSample != SCE_AT9_WORD_LENGTH_16BIT)
			&& (pInWaveHeader->pcmHeader.wBitsPerSample != SCE_AT9_WORD_LENGTH_24BIT)) {
			DPRINTF("This program doesn't support %dbit PCM in encoding mode\n", pInWaveHeader->pcmHeader.wBitsPerSample);
			status = SCE_ERROR_ENCODE_ILLEGAL_BITS_PER_SAMPLE;
			goto fail;
		}
		break;
	case FORMAT_IEEEFLOAT:
		if (pInWaveHeader->pcmHeader.wBitsPerSample != SCE_AT9_WORD_LENGTH_FLOAT) {
			DPRINTF("This program doesn't support IEEE %dbit PCM in encoding mode\n", pInWaveHeader->pcmHeader.wBitsPerSample);
			status = SCE_ERROR_ENCODE_ILLEGAL_BITS_PER_SAMPLE;
			goto fail;
		}
		break;
	default:
		status = SCE_ERROR_ENCODE_ILLEGAL_INPUT_FORMAT;
		goto fail;
		break;
	}

	if (totallen < AT9_MIN_SAMPLES) {
		DPRINTF("too short input file\n");
		DPRINTF("input file has to be larger than %d Samples\n\n", AT9_MIN_SAMPLES);
		status = SCE_ERROR_ENCODE_TOO_SHORT_FILE_SAMPLES;
		goto fail;
	}
 fail:
	return status;
}

static int _checkEncodeExParam(int nbands,
							   int isband,
							   int gradmode)
{
	if (nbands != SCE_AT9_PARAM_UNSET) {
		if ((nbands < 3) || (nbands > 18)) {
			DPRINTF("specified nbands value(%d) exceeds the range\n", nbands);
			return SCE_ERROR_MAIN_OPTION_ILLEGAL_NBANDS;
		}
	}
	if (isband != SCE_AT9_PARAM_UNSET) {
		if ((isband != -1) && ((isband < 3) || (isband > 18))) {
			DPRINTF("specified isband value(%d) exceeds the range\n", isband);
			return SCE_ERROR_MAIN_OPTION_ILLEGAL_ISBAND;
		}
		if (nbands != SCE_AT9_PARAM_UNSET) {
			if (nbands < isband) {
				DPRINTF("specified isband value(%d) exceeds the specified nband value(%d)\n", isband, nbands);
				return SCE_ERROR_MAIN_OPTION_ILLEGAL_ISBAND;
			}
		}
	}
	if (gradmode != SCE_AT9_PARAM_UNSET) {
		if ((gradmode < 0) || (gradmode > 4)) {
			DPRINTF("specified gradmode value(%d) exceeds the range\n", gradmode);
			return SCE_ERROR_MAIN_OPTION_ILLEGAL_GRADMODE;
		}
	}
	return SCE_SUCCESS;
}


static void _displaySupportParam(void)
{
    int index, nCodecIndex;
	
	nCodecIndex = sizeof(gAtracCodecParam) / sizeof(Atrac9CodecParam);

    DPRINTF("This ATRAC9(TM) program supports only the following parameters\n\n");

    for(index = 0; index < nCodecIndex; index++){
		/* Since display items are bitrate, channel, and suterframe, */
		/* only the item whose samplingrate is 48kHz is displayed */
		if (gAtracCodecParam[index].samplingRate == SCE_AT9_SAMPLING_RATE_48KHZ) {
			DPRINTF("bitrate = %3d[kbps], Ch = %1d[ch]", 
					gAtracCodecParam[index].bitrate, 
					gAtracCodecParam[index].ch);
			if (gAtracCodecParam[index].framesInSuperframe == 1) {
				DPRINTF(" superframe OFF");
			} else {
				DPRINTF(" superframe ON");
			}
			if ((gAtracCodecParam[index].ch == SCE_AT9_CHANNEL_STEREO)
				&& (gAtracCodecParam[index].dualMode == TRUE)) {
					DPRINTF(" (DualMode ON)\n");
			} else {
					DPRINTF("\n");
			}
		} else {
			break;
		}
	}
	
	return;
}

static void _displayEncodeMode(Atrac9CodecParam *pAtracCodecParam)
{
	DPRINTF("Encoding %d kbps", pAtracCodecParam->bitrate);
	
	DPRINTF(" (ATRAC9");
	if (pAtracCodecParam->framesInSuperframe == 1) {
		DPRINTF("(superframe OFF)");
	} else {
		DPRINTF("(superframe ON)");
	}
	DPRINTF(")\n");

	return;
}

static int _atracEncCore(FILE *infile,
						 FILE *outfile,
						 Atrac9CodecParam *pAtracCodecParam,
						 int  dualMode,
						 int  nbands,
						 int  isband,
						 int  gradMode,
					     int  inputlength,
						 int  origlength,
						 int  wband,
						 int  bex,
						 int  slc)
{
	int status = SCE_SUCCESS;
	HANDLE_ATRAC9 encHandle;
	int superframeSize;
	int channels;
	int bytesGenerated;
    int	nBytesEncoded;
	unsigned char pcmBuffer[SCE_AT9_MAX_CHANNELS * SCE_AT9_MAX_SUPER_FRAME_SAMPLES * sizeof(int)];
	unsigned char streamBuf[SCE_AT9_MAX_SUPER_FRAME_SIZE];
	SceAt9EncInitParam encInitParam;
	SceAt9EncExtParam  encExtParam;
	int pcmSamples;
	SceAt9CodecInfo codecInfo;
	int terminateFlag;
	int reserved = 0;

	channels = pAtracCodecParam->ch;
	superframeSize = pAtracCodecParam->superframeSize;

	encHandle = sceAt9GetHandle();

	if (encHandle == NULL) {
		DPRINTF("sceAt9GetHandle() = NULL");
		status = SCE_ERROR_ENCODE_CANNOT_GET_HANDLE;
		goto fail;
	}
	if (bex != FALSE) {
		if (wband != FALSE) {
			DPRINTF("bex option and wband option cannot be used together\n");
			return SCE_ERROR_MAIN_OPTION_ILLEGAL_BEX;
		}
		if (pAtracCodecParam->samplingRate != SCE_AT9_SAMPLING_RATE_48KHZ) {
			DPRINTF("bex option cannot be used except the output sampling rate of 48kHz\n");
			return SCE_ERROR_MAIN_OPTION_ILLEGAL_BEX;
		}
		if ((nbands != SCE_AT9_PARAM_UNSET) && ((nbands < 5) || (nbands > 10))) {
			DPRINTF("specified nbands value(%d) exceeds the range with bex option ON\n", nbands);
			return SCE_ERROR_MAIN_OPTION_ILLEGAL_BEX;
		}
		switch (channels) {
		case SCE_AT9_CHANNEL_MONO:
		case SCE_AT9_CHANNEL_STEREO:
			switch (pAtracCodecParam->bitrate / channels) {
			case 36:
			case 48:
			case 60:
			case 72:
				break;
			default:
				DPRINTF("specified bitrate(=%dkbps) has not supported with bex option ON\n", pAtracCodecParam->bitrate);
				return SCE_ERROR_MAIN_OPTION_ILLEGAL_BEX;
				break;
			}
			break;
		default:
			DPRINTF("bex option cannot be used in multichannel\n");
			return SCE_ERROR_MAIN_OPTION_ILLEGAL_BEX;
			break;
		}
	}
	if ((channels != SCE_AT9_CHANNEL_CH5_1) && (channels != SCE_AT9_CHANNEL_CH7_1)) {
		slc = FALSE;
	}
	status = sceAt9EncSetEncParam(encHandle,
								  wband,
								  bex,
								  reserved,
								  slc);
	if (status < 0) {
		DPRINTF("sceAt9EncSetEncParam() = 0x%x\n", status);
		goto fail;
	}

	encInitParam.samplingRate       = pAtracCodecParam->samplingRate;
	encInitParam.channels           = channels;
	encInitParam.dualMode           = dualMode;
	encInitParam.superframeSize     = superframeSize;
	encInitParam.framesInSuperframe = pAtracCodecParam->framesInSuperframe;
	encInitParam.wlength            = pAtracCodecParam->wlength;
	encExtParam.nbands              = nbands;
	encExtParam.isband              = isband;
	encExtParam.gradMode            = gradMode;

	status = sceAt9EncInit(encHandle,
						   &encInitParam,
						   &encExtParam);

	if (status < 0) {
		DPRINTF("sceAt9EncInit() = 0x%x\n", status);

		if ((unsigned int)status == SCE_AT9_ERROR_INTERNAL_ERROR) {
			SceAt9InternalErrorInfo internalErrorInfo;

			sceAt9GetInternalErrorInfo(encHandle, &internalErrorInfo);
			DPRINTF("internalErrorInfo [%d, %d, %d]", internalErrorInfo.errorCode, internalErrorInfo.detailError, internalErrorInfo.detailError);
		}
		goto fail;
	}
	
	status = sceAt9GetCodecInfo(encHandle, &codecInfo);

	if (status < 0) {
		DPRINTF("sceAt9GetCodecInfo() = 0x%x\n", status);
		goto fail;
	}
	status = createAt9Header(outfile,
							 &codecInfo,
							 bex,
							 inputlength);

	if (status < 0) {
		DPRINTF("createAt9Header() = 0x%x\n", status);
		goto fail;
	}

	nBytesEncoded = 0;

	while (inputlength > 0) {
		int encodeSamples = codecInfo.frameSamples * codecInfo.framesInSuperframe;
		
		if (inputlength < encodeSamples) {
			encodeSamples = inputlength;
		}
#ifdef _WIN32
		pcmSamples = (int)fread_s(pcmBuffer, SCE_AT9_MAX_CHANNELS * SCE_AT9_MAX_SUPER_FRAME_SAMPLES * sizeof(int), (pAtracCodecParam->wlength / CHAR_BIT), encodeSamples * channels, infile);
#else /* _WIN32 */
		pcmSamples = (int)fread(pcmBuffer, (pAtracCodecParam->wlength / CHAR_BIT), encodeSamples * channels, infile);
#endif /* _WIN32 */
		if (ferror(infile) != 0) {
			DPRINTF("fread error %d\n", errno);
			status = SCE_ERROR_COMMON_FREAD_ERROR;
			goto fail;
		}
		pcmSamples = pcmSamples / channels;
		inputlength -= pcmSamples;

		status = sceAt9EncEncode(encHandle,
								 pcmBuffer,
								 pcmSamples,
								 streamBuf,
								 &bytesGenerated);

		if (status < 0) {
			DPRINTF("sceAt9EncEncode() = 0x%x\n", status);

			if ((unsigned int)status == SCE_AT9_ERROR_INTERNAL_ERROR) {
				SceAt9InternalErrorInfo internalErrorInfo;

				sceAt9GetInternalErrorInfo(encHandle, &internalErrorInfo);
				DPRINTF("internalErrorInfo [%d, %d, %d]", internalErrorInfo.errorCode, internalErrorInfo.detailError, internalErrorInfo.detailError);
			}
			if ((unsigned int)status == SCE_AT9_ERROR_SHORTAGE_OF_BYTES) {
				DPRINTF("This program failed to encode the file because the bitrate was low.\n");
				DPRINTF("Please change the bitrate and encode the file again.\n");
			}
			goto fail;
		}

		if (bytesGenerated > 0) {
			if (fwrite(streamBuf, 1, bytesGenerated, outfile) < (unsigned int)  bytesGenerated){
				DPRINTF("fwrite error\n");
				status = SCE_ERROR_COMMON_FWRITE_ERROR;
				goto fail;
			}
			nBytesEncoded +=  bytesGenerated;
		}
	}

	terminateFlag = FALSE;
	while ( !terminateFlag ) {
		status = sceAt9EncFlush(encHandle,
								streamBuf,
								&bytesGenerated,
								&terminateFlag);

		if (status < 0) {
			DPRINTF("sceAt9EncFlush() = 0x%x\n", status);

			if ((unsigned int)status == SCE_AT9_ERROR_INTERNAL_ERROR) {
				SceAt9InternalErrorInfo internalErrorInfo;

				sceAt9GetInternalErrorInfo(encHandle, &internalErrorInfo);
				DPRINTF("internalErrorInfo [%d, %d, %d]", internalErrorInfo.errorCode, internalErrorInfo.detailError, internalErrorInfo.detailError);
			}
			goto fail;
		}

		if (bytesGenerated > 0) {
			if (fwrite(streamBuf, 1, bytesGenerated, outfile) < (unsigned int)  bytesGenerated){
				DPRINTF("output error\n");
				status = SCE_ERROR_COMMON_FWRITE_ERROR;
				goto fail;
			}
			nBytesEncoded +=  bytesGenerated;
		}
	}
	/* Check Bitrate */
	if (superframeSize > 0) {
		DPRINTF("Total Encoded Bytes    =%8d Bytes@%dframes(ave=%dbytes)\n",
			   nBytesEncoded, nBytesEncoded/superframeSize , superframeSize);
	}

fail:
	sceAt9ReleaseHandle(encHandle);	
	
	return status;
}
